networks:
  emails:
    driver: "bridge"
version: '2'
services:
  emails:
    networks:
      - "emails"
    container_name: "emails"
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm run build"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # http://dchua.com/2016/02/07/getting-npm-packages-to-be-installed-with-docker-compose/
    ports:
      - "3000:3000"
      - "3001:3001"
